name: Checks
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with: { fetch-depth: 1 }

    - uses: actions/setup-go@v2
      with: { go-version: '1.15' }
    - uses: actions/setup-ruby@v1
      with: { ruby-version: '2.6' }

    - name: install dependencies
      run: PRECOMMAND=sudo make install-checks

    - name: run checks
      run: make checks
